version: "3"
services:
  test_database:
    container_name: mysql8
    image: mysql:8
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./test-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    ulimits:
      # memlock:
      #   soft: -1
      #   hard: -1
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536